backend: 
  name: github
  branch: master
  repo: stefanosu/newgatsbyblog
    
media_folder: static/img 
public_folder: img 

collections: 
- name: "team"
  label: "Team"
  folder: src/team
  create: true 
  slug: '{{slug}}' 
  fields: 
  - { label: "Team member", name: "title", widget: "string" }
  - { label: 'Bio', name: 'bio', widget: 'markdown' }  